# Generated by Django 4.2.3 on 2023-10-07 15:59

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profiel_pricture",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=users.models.profile_picture_upload_path,
            ),
        ),
    ]
