# Generated by Django 4.2.3 on 2023-10-07 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_profiel_pricture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="profiel_pricture",
            new_name="profile_picture",
        ),
    ]
