# Generated by Django 4.2.3 on 2023-11-12 21:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="availabe_funds",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Availabe funds for the user",
                max_digits=10,
            ),
        ),
    ]
