# Generated by Django 4.2.3 on 2023-11-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_availabe_funds"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="availabe_funds",
            new_name="available_funds",
        ),
    ]
