# Generated by Django 4.2.3 on 2023-10-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_event_participants"),
        ("users", "0003_rename_profiel_pricture_customuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(blank=True, to="api.group"),
        ),
    ]
