# Generated by Django 4.2.3 on 2023-12-28 19:36

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_availabe_funds_customuser_available_funds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.FileField(
                blank=True,
                default=users.models.default_icon_image,
                help_text="User provile icon image",
                null=True,
                upload_to=users.models.profile_picture_upload_path,
            ),
        ),
    ]
