# Generated by Django 4.2.3 on 2023-10-17 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={},
        ),
        migrations.AlterModelOptions(
            name="member",
            options={"ordering": ["joined_at"]},
        ),
    ]
