# Generated by Django 4.2.3 on 2023-11-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_event_group_alter_event_organizer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_archived",
            field=models.BooleanField(
                default=False, help_text="Indicates whether the event is archived."
            ),
        ),
    ]
