# Generated by Django 4.2.3 on 2023-11-08 02:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0005_event_is_archived"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bet",
            old_name="user",
            new_name="creator",
        ),
        migrations.AlterUniqueTogether(
            name="bet",
            unique_together={("creator", "event")},
        ),
    ]
