# Generated by Django 4.2.3 on 2023-11-09 17:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0006_rename_user_bet_creator_alter_bet_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bet",
            old_name="creator",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="group",
            old_name="creator",
            new_name="user",
        ),
        migrations.AlterUniqueTogether(
            name="bet",
            unique_together={("user", "event")},
        ),
    ]
