# Generated by Django 4.2.3 on 2023-11-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_creator_bet_user_rename_creator_group_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="bet_type",
            field=models.CharField(
                choices=[("Win", "Win"), ("Lose", "Lose")],
                default="",
                help_text="Select the bet type ('Win' or 'Lose')",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="bet",
            name="team_choice",
            field=models.CharField(
                choices=[("Team 1", "Team 1"), ("Team 2", "Team 2")],
                default="",
                help_text="Select the team you want to bet on",
                max_length=15,
            ),
        ),
    ]
