# Generated by Django 4.2.3 on 2023-11-27 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_bet_points_bet_amount_alter_bet_bet_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="time",
            new_name="start_time",
        ),
        migrations.AddField(
            model_name="event",
            name="end_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="The scheduled end time of the event.",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="is_complete",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the event has been completed.",
            ),
        ),
    ]
