# Generated by Django 4.2.3 on 2023-12-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_rename_time_event_start_time_event_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(
                help_text="The name of the group. Must be unique.",
                max_length=20,
                unique=True,
            ),
        ),
    ]
