# Generated by Django 4.2.3 on 2023-12-23 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_group_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bet",
            old_name="amount",
            new_name="bet_amount",
        ),
    ]
