# Generated by Django 4.2.3 on 2023-12-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_rename_amount_bet_bet_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="team_choice",
            field=models.CharField(
                default="",
                help_text="Select the team you want to bet on",
                max_length=15,
            ),
        ),
    ]
