# Generated by Django 4.2.3 on 2023-12-30 00:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_group_banner_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="bet_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default="0.00",
                help_text="The amount wagered on the bet. Defaults to 0.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
